
// List of neighborhoods for Amman city
export const ammanNeighborhoods = [
  "1st Circle",
  "2nd Circle",
  "3rd Circle",
  "4th Circle",
  "5th Circle",
  "6th Circle",
  "7th Circle",
  "8th Circle",
  "Abdali",
  "Abdoun",
  "Abdoun Al Janobi",
  "Abdoun Al Shamali",
  "Abu Al-Nair",
  "Abu Al-Sous",
  "Abu Alanda",
  "Abu Nsair",
  "Adan",
  "Airport Road - Dunes Bridge",
  "Airport Road - Madaba Bridge",
  "Airport Road - Manaseer Gs",
  "Al Ashrafyeh",
  "Al Bassah",
  "Al Bayader",
  "Al Bnayyat",
  "Al Forousyah",
  "Al Gardens",
  "Al Hashmi Al Janobi",
  "Al Hashmi Al Shamali",
  "Al Hummar",
  "Al Hurryeh",
  "Al Jandaweel",
  "Al Jizah",
  "Al Kamaliya",
  "Al Kursi",
  "Al Lubban",
  "Al Manarah",
  "Al Muqabalain",
  "Al Qastal",
  "Al Qwaismeh",
  "Al Rabiah",
  "Al Rajeeb",
  "Al Rawabi",
  "Al Rawnaq",
  "Al Ridwan",
  "Al Sahl",
  "Al Sina'a",
  "Al Tuneib",
  "Al Urdon Street",
  "Al Yadudah",
  "Al-'Al",
  "Al-Abdaliya",
  "Al-Adlyeh",
  "Al-Amir Hamzah",
  "Al-Awdeh",
  "Al-Baida",
  "Al-Dhuheibah",
  "Al-Dhuheibah Al-Gharbiyah",
  "Al-Dia'",
  "Al-Diyar",
  "Al-Dmeenah",
  "Al-Dmenah",
  "Al-Feisal",
  "Al-Fuhais",
  "Al-Humranyah",
  "Al-Husnyeh",
  "Al-Iman",
  "Al-Jabal Al-Akhdar",
  "Al-Jumayyil",
  "Al-Jweideh",
  "Al-Khadra'",
  "Al-Khaznah",
  "Al-Khreim",
  "Al-Kom Al-Gharbi",
  "Al-Kom Al-Sharqi",
  "Al-Kutaifah",
  "Al-Ma'adi",
  "Al-Mahatta",
  "Al-Mansour",
  "Al-Marqab",
  "Al-Mashqar",
  "Al-Mugairat",
  "Al-Mushatta",
  "Al-Mustanada",
  "Al-Muwaqqar",
  "Al-Naharyah",
  "Al-Nuqairah",
  "Al-Oroubah",
  "Al-Qasabat",
  "Al-Quneitirah",
  "Al-Qusour",
  "Al-Rabwa",
  "Al-Rajila",
  "Al-Raqim",
  "Al-Rjoum",
  "Al-Shabah",
  "Al-Thra",
  "Al-Thuheir",
  "Al-Wehdat",
  "Al-Yarmouk",
  "Al-Zafaran",
  "Al-Zahra",
  "Al-Zamila",
  "Al-Zaytouneh",
  "Alkhashafia",
  "Almih St",
  "Areinba Al Gharbiyah",
  "Areinba Al Sharqiyah",
  "Arjan",
  "As Sarou",
  "Ayn Rbat",
  "Badr",
  "Badr Jdedeh",
  "Bahath",
  "Baqa'a Camp",
  "Basman",
  "Bilal",
  "Birayn",
  "Dab'a",
  "Dabouq",
  "Daheit Al Ameer Hasan",
  "Daheit Al Aqsa",
  "Daheit Al Rasheed",
  "Daheit Al Yasmeen",
  "Daheit Al-Haj Hassan",
  "Dahiet Al Ameer Ali",
  "Dahiet Al Ameer Rashed",
  "Dahiet Al Hussain",
  "Dahiet Al-Istiqlal",
  "Dahiet Al-Nakheel",
  "Dahiet Al-Rawda",
  "Deir Ghbar",
  "Dhuheibah Al-Sharqiyah",
  "Downtown",
  "Hai Nazzal",
  "Hay Al Rahmanieh",
  "Hay Albarakeh",
  "Hay Alkhaledeen",
  "Hay Alsaleheen",
  "Hettin",
  "Hjar Al Nawabilseh",
  "Howarah",
  "Husban",
  "Iraq Al Ameer",
  "Jabal Al Hussain",
  "Jabal Al Naser",
  "Jabal Al Nuzha",
  "Jabal Al Zohor",
  "Jabal Al-Jofah",
  "Jabal Al-Lweibdeh",
  "Jabal Al-Marrikh",
  "Jabal Al-Nathif",
  "Jabal Al-Taj",
  "Jabal Amman",
  "Jawa",
  "Jelul",
  "Jubaiha",
  "Khalda",
  "khan Al-Zabib",
  "Khirbet Sooq",
  "Madonna",
  "Mahes",
  "Marj Al-Furs",
  "Marj El Hamam",
  "Marka",
  "Marka Al Janoubiya",
  "Marka Al Shamaliya",
  "Mecca Street",
  "Medina Street",
  "Mobes",
  "Naour",
  "Qafor",
  "Rajm Al-Shof",
  "Rajm Amesh",
  "Ras El Ain",
  "Rujm ash Shami",
  "Safut",
  "Sahab",
  "Salem",
  "Salihiyat Al-Abid",
  "Shafa Badran",
  "Shmaisani",
  "Sports City",
  "Sufa",
  "Swefieh",
  "Swelieh",
  "Tabarboor",
  "Tla' Al Ali Al Shamali",
  "Tla' Al Ali Al Sharqi",
  "Tla' Ali",
  "Tloo' Al-Misdar",
  "Um al Basateen",
  "Um Batma",
  "Um El Summaq",
  "Um Rummanah",
  "Um Uthaiena",
  "Um Uthaiena Al Gharbi",
  "Um Uthaiena Al Sharqi",
  "Umm A-Dananir",
  "Umm al Kundum",
  "Umm Al-Amad",
  "Umm Al-Rasas",
  "Umm Al-Usoud",
  "Umm Nowarah",
  "Umm Quseir",
  "Umm Shterat",
  "Umm Zuwaytinah",
  "University Street",
  "Uyun Al-Dhib",
  "Wadi Al Haddadeh",
  "Wadi Al-Eish",
  "Wadi Al-Srour",
  "Wadi Al-Tay",
  "Wadi El Seer",
  "Wadi Saqra",
  "Yajouz",
  "Zabboud",
  "Zeinab",
  "Zinat Al-Rubue",
  "Zumlat al Ulya",
  "Zuwayza",
  "Other"
];

// List of major Jordan cities
export const jordanCities = [
  "Amman",
  "Zarqa",
  "Irbid",
  "Aqaba",
  "Madaba",
  "Jerash",
  "Ajloun",
  "Salt",
  "Mafraq",
  "Karak",
  "Ma'an",
  "Tafilah"
];
