// List of neighborhoods for Amman city
export const ammanNeighborhoods = [
  "1st Circle",
  "2nd Circle",
  "3rd Circle",
  "4th Circle",
  "5th Circle",
  "6th Circle",
  "7th Circle",
  "8th Circle",
  "Abdali",
  "Abdoun",
  "Abdoun Al Janobi",
  "Abdoun Al Shamali",
  "Abu Al-Nair",
  "Abu Al-Sous",
  "Abu Alanda",
  "Abu Nsair",
  "Adan",
  "Airport Road - Dunes Bridge",
  "Airport Road - Madaba Bridge",
  "Airport Road - Manaseer Gs",
  "Al Ashrafyeh",
  "Al Bassah",
  "Al Bayader",
  "Al Bnayyat",
  "Al Forousyah",
  "Al Gardens",
  "Al Hashmi Al Janobi",
  "Al Hashmi Al Shamali",
  "Al Hummar",
  "Al Hurryeh",
  "Al Jandaweel",
  "Al Jizah",
  "Al Kamaliya",
  "Al Kursi",
  "Al Lubban",
  "Al Manarah",
  "Al Muqabalain",
  "Al Qastal",
  "Al Qwaismeh",
  "Al Rabiah",
  "Al Rajeeb",
  "Al Rawabi",
  "Al Rawnaq",
  "Al Ridwan",
  "Al Sahl",
  "Al Sina'a",
  "Al Tuneib",
  "Al Urdon Street",
  "Al Yadudah",
  "Al-'Al",
  "Al-Abdaliya",
  "Al-Adlyeh",
  "Al-Amir Hamzah",
  "Al-Awdeh",
  "Al-Baida",
  "Al-Dhuheibah",
  "Al-Dhuheibah Al-Gharbiyah",
  "Al-Dia'",
  "Al-Diyar",
  "Al-Dmeenah",
  "Al-Dmenah",
  "Al-Feisal",
  "Al-Fuhais",
  "Al-Humranyah",
  "Al-Husnyeh",
  "Al-Iman",
  "Al-Jabal Al-Akhdar",
  "Al-Jumayyil",
  "Al-Jweideh",
  "Al-Khadra'",
  "Al-Khaznah",
  "Al-Khreim",
  "Al-Kom Al-Gharbi",
  "Al-Kom Al-Sharqi",
  "Al-Kutaifah",
  "Al-Ma'adi",
  "Al-Mahatta",
  "Al-Mansour",
  "Al-Marqab",
  "Al-Mashqar",
  "Al-Mugairat",
  "Al-Mushatta",
  "Al-Mustanada",
  "Al-Muwaqqar",
  "Al-Naharyah",
  "Al-Nuqairah",
  "Al-Oroubah",
  "Al-Qasabat",
  "Al-Quneitirah",
  "Al-Qusour",
  "Al-Rabwa",
  "Al-Rajila",
  "Al-Raqim",
  "Al-Rjoum",
  "Al-Shabah",
  "Al-Thra",
  "Al-Thuheir",
  "Al-Wehdat",
  "Al-Yarmouk",
  "Al-Zafaran",
  "Al-Zahra",
  "Al-Zamila",
  "Al-Zaytouneh",
  "Alkhashafia",
  "Almih St",
  "Areinba Al Gharbiyah",
  "Areinba Al Sharqiyah",
  "Arjan",
  "As Sarou",
  "Ayn Rbat",
  "Badr",
  "Badr Jdedeh",
  "Bahath",
  "Baqa'a Camp",
  "Basman",
  "Bilal",
  "Birayn",
  "Dab'a",
  "Dabouq",
  "Daheit Al Ameer Hasan",
  "Daheit Al Aqsa",
  "Daheit Al Rasheed",
  "Daheit Al Yasmeen",
  "Daheit Al-Haj Hassan",
  "Dahiet Al Ameer Ali",
  "Dahiet Al Ameer Rashed",
  "Dahiet Al Hussain",
  "Dahiet Al-Istiqlal",
  "Dahiet Al-Nakheel",
  "Dahiet Al-Rawda",
  "Deir Ghbar",
  "Dhuheibah Al-Sharqiyah",
  "Downtown",
  "Hai Nazzal",
  "Hay Al Rahmanieh",
  "Hay Albarakeh",
  "Hay Alkhaledeen",
  "Hay Alsaleheen",
  "Hettin",
  "Hjar Al Nawabilseh",
  "Howarah",
  "Husban",
  "Iraq Al Ameer",
  "Jabal Al Hussain",
  "Jabal Al Naser",
  "Jabal Al Nuzha",
  "Jabal Al Zohor",
  "Jabal Al-Jofah",
  "Jabal Al-Lweibdeh",
  "Jabal Al-Marrikh",
  "Jabal Al-Nathif",
  "Jabal Al-Taj",
  "Jabal Amman",
  "Jawa",
  "Jelul",
  "Jubaiha",
  "Khalda",
  "khan Al-Zabib",
  "Khirbet Sooq",
  "Madonna",
  "Mahes",
  "Marj Al-Furs",
  "Marj El Hamam",
  "Marka",
  "Marka Al Janoubiya",
  "Marka Al Shamaliya",
  "Mecca Street",
  "Medina Street",
  "Mobes",
  "Naour",
  "Qafor",
  "Rajm Al-Shof",
  "Rajm Amesh",
  "Ras El Ain",
  "Rujm ash Shami",
  "Safut",
  "Sahab",
  "Salem",
  "Salihiyat Al-Abid",
  "Shafa Badran",
  "Shmaisani",
  "Sports City",
  "Sufa",
  "Swefieh",
  "Swelieh",
  "Tabarboor",
  "Tla' Al Ali Al Shamali",
  "Tla' Al Ali Al Sharqi",
  "Tla' Ali",
  "Tloo' Al-Misdar",
  "Um al Basateen",
  "Um Batma",
  "Um El Summaq",
  "Um Rummanah",
  "Um Uthaiena",
  "Um Uthaiena Al Gharbi",
  "Um Uthaiena Al Sharqi",
  "Umm A-Dananir",
  "Umm al Kundum",
  "Umm Al-Amad",
  "Umm Al-Rasas",
  "Umm Al-Usoud",
  "Umm Nowarah",
  "Umm Quseir",
  "Umm Shterat",
  "Umm Zuwaytinah",
  "University Street",
  "Uyun Al-Dhib",
  "Wadi Al Haddadeh",
  "Wadi Al-Eish",
  "Wadi Al-Srour",
  "Wadi Al-Tay",
  "Wadi El Seer",
  "Wadi Saqra",
  "Yajouz",
  "Zabboud",
  "Zeinab",
  "Zinat Al-Rubue",
  "Zumlat al Ulya",
  "Zuwayza",
  "Other"
];

// List of neighborhoods for Ajloun
export const ajlounNeighborhoods = [
  "A'anjara",
  "A'fna",
  "Al-Hashimiyyah",
  "Alqala'a",
  "Barqash",
  "Downtown",
  "E'in Jana",
  "I'bbeen",
  "Kuforanja",
  "Sakhra",
  "Other"
];

// List of neighborhoods for Al Karak
export const karakNeighborhoods = [
  "A'i",
  "Ader",
  "Al Msherifeh",
  "Al-Adnanya",
  "Al-Marj",
  "Al-Mazar Al-Janoubi",
  "Al-Qasr",
  "Al-Qatraneh",
  "Al-Rabba",
  "Al-Smeikhiyyeh",
  "Al-Thaniyyah",
  "Faqqu'",
  "GhorAl Safi",
  "Manshiyyet Abu Hammour",
  "Mu'ta",
  "Qusoor Bashir",
  "That Ras",
  "Zohoom",
  "Other"
];

// List of neighborhoods for Aqaba
export const aqabaNeighborhoods = [
  "Al Atiba'",
  "Al Balad Al Qadeemeh",
  "Al Herafeyeh",
  "Al Mahdood Al Gharby",
  "Al Mahdood Al Sharqy",
  "Al Mahdood Al Wasat",
  "Al Manarah",
  "Al Mulqan",
  "Al Ridwan",
  "Al Rimaal",
  "Al Sakaneyeh 10",
  "Al Sakaneyeh 3",
  "Al Sakaneyeh 5",
  "Al Sakaneyeh 6",
  "Al Sakaneyeh 7",
  "Al Sakaneyeh 9",
  "Al Shalalah",
  "Al-Alamiya",
  "Al-Markaziya",
  "Al-Nakhil",
  "Al-Sakaneyeh 8",
  "Al-Shaabiyah",
  "Al-Shamiyah",
  "Ayla",
  "Karama",
  "Mulqan Janoubi",
  "Mulqan Shamali",
  "Qweira",
  "Sakan Al Asmedah",
  "Tala Bay",
  "Wadi Rum",
  "Other"
];

// List of neighborhoods for Irbid
export const irbidNeighborhoods = [
  "30 Street",
  "Aban",
  "Abu Sidu",
  "Al Afrah",
  "Al Andalus",
  "Al Ashrafiyah",
  "Al Balad",
  "Al Barha",
  "Al Barha Street",
  "Al Dorra Circle",
  "Al Eiadat Circle",
  "Al Hay Al Gharby",
  "Al Hay Al Janooby",
  "Al Hay Al Sharqy",
  "Al Hisbeh Al Markizeya",
  "Al Husn",
  "Al Huson Street",
  "Al Lawazem Circle",
  "Al Madinah Al Sena'eiah",
  "Al Madrase Al Shamela",
  "Al Mal'ab Al Baladi",
  "Al Matla'",
  "Al Mazar Al-Shamali",
  "Al Naseem Circle",
  "Al Nuzha",
  "Al Qubeh Circle",
  "Al Quds Street",
  "Al Rabiah",
  "Al Rahebat Al Wardiah",
  "Al Sareeh",
  "Al Sonbola",
  "Al Souq",
  "Al Thaqafa Circle",
  "Al-Adasiya",
  "Al-Baqoura",
  "Al-Hashmy Street",
  "Al-Kharaj",
  "Al-Mahari'a",
  "Al-Manara",
  "Al-Manshiya",
  "Al-Mokhaba Al-Tahta",
  "Al-Mughayer",
  "Al-Rawdah",
  "Al-Tal",
  "Al-Zamaliya",
  "Alal",
  "Albayyada Circle",
  "An-Nuayyimah",
  "Arhaba",
  "Aydoun",
  "Bait Ras",
  "Barashta",
  "Basila",
  "Bayt Idis",
  "Bayt Yafa",
  "Behind Safeway",
  "Bushra",
  "Daheit Al Ameer Rashed",
  "Daheit Al Hussain",
  "Dayr as Si'nah",
  "Dayr Yusuf",
  "Der Abi Saeed",
  "Duwaqarah",
  "Eidoon Military Hospital",
  "Fo'ara",
  "Fo'ara Street",
  "Ghorfat Al Tejara",
  "Habka",
  "Hakama",
  "Hakama Street",
  "Ham",
  "Harima",
  "Hartha",
  "Hasan Al Tal Mosque",
  "Hatim village",
  "Hawr",
  "Hay Al Abraar",
  "Hay Al Qaselah",
  "Hay Al Turokman",
  "Hay Al Worood",
  "Hay Al Zohoor",
  "Hay Alia",
  "Hay Altlool",
  "Hay Twaal",
  "Hibras",
  "Hofa",
  "Honaina",
  "Huwwarah",
  "Inba",
  "Irbid Girl's College",
  "Irbid Mall",
  "Isharet Al Darawshe",
  "Isharet Al Iskan",
  "Isharet Al Malika Noor",
  "Iskan Al A'mileen",
  "Iskan Al Atiba'",
  "Iskan Al Dobbat",
  "Iskan Al Mohandeseen",
  "Jajin",
  "Jefen",
  "Johfiyeh",
  "Judayta",
  "Jumha",
  "Kharja",
  "Kherbet Qasem",
  "Khirbat Al-Borz",
  "King Abdullah II Gardens",
  "King Abdullah University Hospital",
  "Kitim",
  "Kofor Youba",
  "Kufr Abeel",
  "Kufr Asad",
  "Kufr Awan",
  "Kufr Jayez",
  "Kufr Ma'",
  "Kufr Rakeb",
  "Kufr Sowm",
  "Kuraimah",
  "Makhraba",
  "Malka",
  "Mandah",
  "Maru",
  "Mojamma' Al Aghwaar Al Jadeed",
  "Mojamma' Al Shamal",
  "Mojamma' Alshaikh Khaleel",
  "Mojamma' Amman Al Jadeed",
  "Natifa",
  "North Shuna",
  "Palestine Street",
  "Petra Street",
  "Princess Basma Hospital",
  "Qaraqosh",
  "Qum",
  "Qumaym",
  "Sahara Circle",
  "Sahm",
  "Saidour",
  "Sal",
  "Sal Circle",
  "Salet Al Sharq",
  "Sama Al-Rousan",
  "Samad",
  "Samad Village",
  "Samar",
  "Sammou",
  "Seil Al-Himma",
  "Shajara",
  "Sharekat Al Kahraba Circle",
  "Shatna",
  "Shaykh Hussein",
  "Smma",
  "Sum",
  "Tabaqet Fahel",
  "Taqbal",
  "Taybeh District",
  "Tibneh",
  "Umm Al-Jadayel",
  "Umm Qais",
  "University of Science and Technology",
  "University Street",
  "Wadi Al-Rayyan",
  "Waqqas",
  "Yabla",
  "Zabda",
  "Zhr",
  "Zubiya",
  "Other"
];

// List of neighborhoods for Jerash
export const jerashNeighborhoods = [
  "Nihla",
  "Al-Haddadeh",
  "Al-Hashimiyyah",
  "Al-Kittah",
  "Al-Majdal",
  "Al-Mastaba",
  "Al-Msherifeh",
  "Al-Naseem",
  "Al-Rashaida",
  "Amamah",
  "Borma",
  "Dahl",
  "Debbin",
  "Kufair",
  "Kufor Khal",
  "Marsa'",
  "Qafqafa",
  "Sakib",
  "Salhoub",
  "Soof",
  "Tal Al-Rumman",
  "Unaybah",
  "Other"
];

// List of neighborhoods for Jordan Valley
export const jordanValleyNeighborhoods = [
  "Al Rama",
  "Baptist",
  "Dead Sea",
  "Ghor Al Kafrain",
  "Other"
];

// List of neighborhoods for Ma'an
export const maanNeighborhoods = [
  "Al-Hussainiyyah",
  "Al-Mraigha",
  "Al-Shobak",
  "Ayl",
  "Bayda",
  "Jafr",
  "Jaya",
  "Ma'an Qasabah",
  "Najl",
  "Petra",
  "Ras An-Naqab",
  "Sath Ma'an",
  "Shmakh",
  "Um Sayhoon",
  "Wadi Musa",
  "Other"
];

// List of neighborhoods for Madaba
export const madabaNeighborhoods = [
  "Al Nasser",
  "Al Nnozha",
  "Al-Faisaliyyah",
  "Al-Fayha'",
  "Al-Imam Al-Ghazali",
  "Al-Jbeil",
  "Al-Mokhayam",
  "Al-Zafaran",
  "Dalilet Al-Hamaideh",
  "Hanina",
  "Hanina Al-Gharbiyyah",
  "Jelul",
  "Juraynah",
  "lob",
  "Madaba Center",
  "Mai'n",
  "Manja",
  "Mkawer",
  "Thiban",
  "Umm Al Amad",
  "Other"
];

// List of neighborhoods for Mafraq
export const mafraqNeighborhoods = [
  "Ain wa Al-Ma'mariyyeh",
  "Al Ghadeer Al Abyad",
  "Al Mazzeh",
  "Al-Ba'ij",
  "Al-Badiah Ash-Shamaliyah",
  "Al-Badiah Ash-Shamaliyah Al-Gharbiya",
  "Al-Bustan",
  "Al-Dafyana",
  "Al-Dajaniya",
  "Al-Daqusma",
  "Al-Hamra",
  "Al-Hay Al-Hashmi",
  "Al-Hay Al-Janoubi",
  "Al-Khalidya",
  "Al-Khirba Al-Samra",
  "Al-Mabruka",
  "Al-Marajim",
  "Al-Mazraa",
  "Al-Nithamiya",
  "Al-Rashada",
  "Al-Rfa'iyat",
  "Al-Salhiya",
  "Al-Za'atari",
  "Al-Zaytouna",
  "Bala'ama",
  "Bowaydet Al Hawamdeh",
  "Bweida Al-Ilimat",
  "Dahiyat Al-Jamaa",
  "Dahl",
  "Dayr Al-Kahf",
  "Fa'",
  "Hai Nowarah",
  "Hawshah",
  "Hay Al-Dobbat",
  "Hay Al-Hussein",
  "Hay Al-Zohoor",
  "Hayyan Al Moshref",
  "Hayyan Rwaibed",
  "Hweishan",
  "Idoun",
  "Koum Al-Ahmar",
  "Manshiyyet Bani Hassan",
  "Mansoura",
  "Mughayyer Al-Sarhan",
  "Nadira",
  "Nayfa",
  "rahbat Rakad",
  "Rhab",
  "Ruwaished",
  "Sabha",
  "Safawi",
  "Sama As-Sirhan",
  "Tayeb Isim",
  "Thaghrat Al-Gub",
  "Um Al Jimal",
  "Um Al Na'am Al Gharbiyyeh",
  "Um Al Na'am Al Sharqiyyeh",
  "Um Al-Lulu",
  "Um Batima",
  "Um Sweiweina",
  "Umm Al-Quttayn",
  "Zamlat Al-Amir Ghazi",
  "Znaya",
  "Other"
];

// List of neighborhoods for Ramtha
export const ramthaNeighborhoods = [
  "Al Bweida",
  "Al Hai Al Gharbi",
  "Al Shajara",
  "Al Thneibeh",
  "Al Torra",
  "Amrawa",
  "Romtha",
  "Other"
];

// List of neighborhoods for Salt
export const saltNeighborhoods = [
  "A'llan",
  "Abu Nsair",
  "Al Balqa'",
  "Al I'zariyyeh",
  "Al Jada'a",
  "Al Jadoor",
  "Al Khader",
  "Al Khandaq",
  "Al Maghareeb",
  "Al Manshiyyeh",
  "Al Midan",
  "Al NAqab",
  "Al Qala'a",
  "Al Remeimeen",
  "Al Salalem",
  "Al Saro",
  "Al Sawarfeh",
  "Al Subeihi",
  "Al Zohour",
  "Al-Sleihi",
  "Deir Alla",
  "Ein Al-Basha",
  "Hay Al Kharabsheh",
  "I'ra",
  "Jala'd",
  "Kafr Hooda",
  "Naqb Al Daboor",
  "Seehan",
  "Shafa Al-Amriya",
  "South Shuna",
  "Swemeh",
  "Um Aldananir",
  "Um Jozeh",
  "Wadi Shua'ib",
  "Yarga",
  "Zay",
  "Other"
];

// List of neighborhoods for Tafila
export const tafilaNeighborhoods = [
  "Al-Ayes",
  "Al-Hasa",
  "Al-Qadisiyyah",
  "Al-Qasr",
  "Al-Rashadiyyah",
  "Bseira",
  "Dana",
  "Jurf Al-Daraweesh",
  "Other"
];

// List of neighborhoods for Zarqa
export const zarqaNeighborhoods = [
  "Hay AlAmeer Abullah",
  "Abu Al-Zighan",
  "Al Autostrad",
  "Al ghweariyyeh",
  "Al Hashemieh",
  "Al Hawooz",
  "Al Jaish Street",
  "Al mantika Al Hurra",
  "Al Mshairfeh",
  "Al Souq",
  "Al Sukhneh",
  "Al Tatweer Al Hadari",
  "Al Tatweer Al Hadari Rusaifah",
  "Al Thawrah Al Arabia Al Kubrah",
  "Al Zarqa Al Jadeedeh",
  "Al Zawahra",
  "Al-Alouk",
  "Al-Bustan",
  "Al-Ghabawi",
  "Al-Kamsha",
  "Al-Misfat st.",
  "Al-Nasir",
  "Al-Qadisyeh - Rusaifeh",
  "Al-Qnaiya",
  "Al-Saadeh st.",
  "Ar-Ruhayl",
  "Awajan",
  "Azraq",
  "Birayn",
  "Daheit Makka Al-Mokarameh",
  "Dahiet Al Amera Haya",
  "Dahiet Al Madena Al Monawwara",
  "Dhlail",
  "Douqara",
  "Graiba",
  "Graisa",
  "Hay Al Ameer Mohammad",
  "Hay Al Hussain",
  "Hay Al Iskan",
  "Hay Al Jundi",
  "Hay Al Nuzha",
  "Hay Al-Rasheed - Rusaifeh",
  "Hay Ja'far Al-Tayyar",
  "Hay Ma'soom",
  "Hay Ramzi",
  "Hay Shaker",
  "Hettin Camp",
  "Iskan Al Batrawi",
  "Iskan Talal - Rusaifeh",
  "Jabal Al Abyad",
  "Jabal Al Ameer Faisal",
  "Jabal Al Ameer Hamza",
  "Jabal Al Ameer Hasan",
  "Jabal Al Amera Rahma",
  "Jabal Al Mugheir",
  "Jabal El Shamali Rusaifeh",
  "Jabal Tareq",
  "Jana'a",
  "Khou",
  "Madinet El Sharq",
  "Qasr al-Hallabat Al-Gharbi",
  "Qasr al-Hallabat Al-Sharqi",
  "Rajm Al Shawk",
  "Rusaifeh El Janoobi",
  "Russayfah",
  "Sarout",
  "Shomer",
  "Um Rummanah",
  "Umm Sleih",
  "Wadi Al Aash",
  "Wadi Al Hajar",
  "Zarqa Private University",
  "Other"
];

// Create a mapping of cities to their neighborhoods
export const cityNeighborhoods: Record<string, string[]> = {
  "Amman": ammanNeighborhoods,
  "Zarqa": zarqaNeighborhoods,
  "Irbid": irbidNeighborhoods,
  "Aqaba": aqabaNeighborhoods,
  "Madaba": madabaNeighborhoods,
  "Jerash": jerashNeighborhoods,
  "Ajloun": ajlounNeighborhoods,
  "Salt": saltNeighborhoods,
  "Mafraq": mafraqNeighborhoods,
  "Karak": karakNeighborhoods,
  "Ma'an": maanNeighborhoods,
  "Tafilah": tafilaNeighborhoods,
  "Ramtha": ramthaNeighborhoods,
  "Jordan Valley": jordanValleyNeighborhoods
};

// List of major Jordan cities
export const jordanCities = [
  "Amman",
  "Zarqa",
  "Irbid",
  "Aqaba",
  "Madaba",
  "Jerash",
  "Ajloun",
  "Salt",
  "Mafraq",
  "Karak",
  "Ma'an",
  "Tafilah",
  "Ramtha",
  "Jordan Valley"
];
