// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbjmujkzeyxwvqkitinc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiam11amt6ZXl4d3Zxa2l0aW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTc5NTMsImV4cCI6MjA2MTY3Mzk1M30.XcYU7J8sGWcb5KZ0Pzq3_8YajeqvpHNTs9hDIbq3G3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);